OPENG-2066: Verify and double-check prometheus alert rules
canonical/tempo-k8s-operator pull request #104
Opened 2024-05-03 08:29 UTC by michaeldmitry

## Issue
Missing Prometheus alert rules.

## Solution
Added some [Grafana Tempo mixin alerts](https://github.com/grafana/tempo/blob/main/operations/tempo-mixin-compiled/alerts.yaml) + our custom rules that should be relevant/basic to users.

2024-05-03 16:00 UTC, mmkay requested changes
Nice work! I tested the queries on my tempo instance. 

I have several remarks to the thresholds set in the alerts. I also think we could merge all these alert rules into a single file - that would be similar to how [mixins define their alerts](https://github.com/grafana/tempo/blob/main/operations/tempo-mixin-compiled/alerts.yaml).

2024-05-06 08:28 UTC, michaeldmitry commented on src/prometheus_alert_rules/tempo_distributor_push_latency.rule
> +expr:  histogram_quantile(0.99, sum by(le) (rate(tempo_distributor_push_duration_seconds_bucket[5m]))) > 1
I think in terms of a disributor pushing to an ingester, it should not be a costly operation; its merely passing on the request (judging on what the live data showed as well). I agree on the tiers part, but I think the threshold might be a bit lower?

2024-05-06 08:32 UTC, mmkay commented on src/prometheus_alert_rules/tempo_distributor_unhealthy.rule
> +alert: TempoDistributorUnhealthy
I think as long as we make sure it doesn't alert now because data is missing we can keep it.

2024-05-06 08:33 UTC, mmkay commented on src/prometheus_alert_rules/tempo_distributor_push_latency.rule
> +expr:  histogram_quantile(0.99, sum by(le) (rate(tempo_distributor_push_duration_seconds_bucket[5m]))) > 1
A bit for sure, but I'd be more worried about failing operations than slow operations - so not sure if there really is a need for a critical alert here.

2024-05-06 08:35 UTC, michaeldmitry commented on src/prometheus_alert_rules/tempo_distributor_unhealthy.rule
> +alert: TempoDistributorUnhealthy
It doesn't trigger. the expression will show "no data" not a valid value, like 0

2024-05-06 08:40 UTC, michaeldmitry commented on src/prometheus_alert_rules/tempo_distributor_push_latency.rule
> +expr:  histogram_quantile(0.99, sum by(le) (rate(tempo_distributor_push_duration_seconds_bucket[5m]))) > 1
no exposed label in that metric or a dedicated metric to show info about "failing" distributor requests. The one that shows failures in distributors is the "TempoDistributorUnhealthy" 
In that case, I'd leave it to warning.

2024-05-06 18:28 UTC, mmkay approved these changes
Looks good!

2024-05-06 18:28 UTC, merged