remove stale opentelemetry_sdk packages
canonical/tempo-k8s-operator pull request #151
Opened 2024-07-24 20:56 UTC by ca-scribner

This hack mitigate an issue where the otel library's mechanism to discover resource detectors raised an Exception after a charm refresh, as described in https://github.com/canonical/grafana-agent-operator/issues/146.  That was caused by a juju/charmcraft issue (https://bugs.launchpad.net/juju/+bug/2058335) where, when upgrading packages, Juju leaves behind package metadata from the old versions.  This caused otel's discovery mechanism to incorrectly use the old resource detector, leading to an exception.

The fix here is to, before the otel discovery mechanism fires, detect if we have multiple "opentelemetry_sdk" distributions (packages) and if we do, delete any that appear to be stale (where "stale" is determined by whether they present `entry_points` - this assumption worked in testing, but not sure if it is universally valid)

## Issue

## Solution

## Context

## Testing Instructions

## Release Notes

2024-07-25 08:07 UTC, PietroPasotti commented
I'm not really happy to do this on each `trace_charm` call (i.e. on every hook).

How about we only run that conditionally on:
```
if os.getenv("JUJU_HOOK_PATH") == "hooks/upgrade-charm":
    ...
```

Also please let's add a test for it.

A better solution IMHO would be do this for each library from ops as a temporary workaround until juju fixes theirs. I can pursue that while we go on with this as a hotfix.

2024-07-25 13:14 UTC, ca-scribner commented
+1 to putting behind a guard to only run on upgrade-charm.

I'm +1 to adding tests too, but wasn't sure the right balance of correctness and destructiveness :D  We could do a full-fidelity unit test, but the test would have to insert stuff into its venv which, if it goes wrong, could be messy.

Maybe an integration test is possible, but the test would have to do something like:
* deploy a broken charm from charmhub (must be from charmhub, otherwise the bug doesn't occur)
* build a new version of that charm using the current lib
* refresh to the new version (this might have to be deployed from charmhub.  I'd need to confirm that)

2024-07-25 18:44 UTC, ca-scribner commented
Added a guard.  Also ignored the type errors as I think the issue is a lack of typing in the source objects?  But I'm a typing noob so might be wrong

2024-07-25 19:55 UTC, ca-scribner commented
If we implement this, I'll need to test the guard some more.  Did a quick test on the grafana-agent charm and I don't think this guard worked (or rather, it was too aggressive - the charm still went into error so I dont think the directory was purged)

2024-07-26 11:34 UTC, PietroPasotti commented
envvar name: JUJU_DISPATCH_PATH

2024-07-26 17:38 UTC, ca-scribner commented
I've updated the PR to use the correct environment variable, and tested it locally for grafana-agent.  Everything works using the reproduction procedure given in this PR description.  Automated tests have not been added here because of how awkward the testing would be.

Given the odd nature of this bug and lack of automatic testing, it would be great if someone else can independently try the grafana-agent fix in case I've missed something

2024-07-29 10:55 UTC, PietroPasotti requested changes

2024-07-29 10:55 UTC, PietroPasotti commented on lib/charms/tempo_k8s/v1/charm_tracing.py
> +        # If there are more than 2, inspect them and infer that any with 0 entrypoints are stale
```suggestion
        # If there is more than 1, inspect each and if it has 0 entrypoints then infer that it is stale
```

2024-07-29 10:55 UTC, PietroPasotti commented on lib/charms/tempo_k8s/v1/charm_tracing.py
> +    """Hack to remove stale opentelemetry sdk packages from the environment.
```suggestion
    """Hack to remove stale opentelemetry sdk packages from the charm's python virtual environment.
```

2024-07-29 10:55 UTC, PietroPasotti commented on lib/charms/tempo_k8s/v1/charm_tracing.py
> +            for d in otel_sdk_distributions:
`d` --> `distribution`

2024-07-29 11:05 UTC, PietroPasotti commented on lib/charms/tempo_k8s/v1/charm_tracing.py
> +        _remove_stale_otel_sdk_packages()
I'm not super convinced it's enough to do it here, perhaps we should apply the patch on module import. Only a problem if charmers use the otlp SDK to set up their own tracers before the charm inits (which is a very edge case), so for now let's choose to ignore it

2024-07-29 11:07 UTC, PietroPasotti approved these changes

2024-07-29 13:29 UTC, ca-scribner commented
ty for the edits - lgtm!

2024-07-30 14:44 UTC, merged